"""hl

Revision ID: b3475daf9170
Revises: 789cd0551468
Create Date: 2020-09-09 14:39:00.343806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3475daf9170'
down_revision = '789cd0551468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('discord_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'user', ['discord_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'discord_id')
    # ### end Alembic commands ###
